server:
  port: 8890
# 2.2.0及以上版本
rocketmq:
  name-server: 192.168.36.11:9876
  producer:
    group: my-group
    sendMessageTimeout: 30000


#spring:
#  rocketmq:
#    nameServer: 192.168.36.11:9876
#    producer:
#      group: my-group