
server:
  port: 9997

redis:
  port: 6379
  host: 192.168.36.11
  password: root

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.36.11:3306/sec_kill?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# 2.2.0及以上版本
rocketmq:
  name-server: 192.168.36.11:9876
  producer:
    group: my-group
    sendMessageTimeout: 30000